[project]
name = "dotfiles"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "==3.14.2"
dependencies = [
    "black>=26.1.0",
    "isort>=7.0.0",
    "matplotlib==3.10.8",
    "mypy==1.19.1",
    "numpy==2.4.2",
    "pillow==12.1.0",
]
